name: Read Text File and Print Content

on:
  push:
    branches:
      - main  # Specify the branch you want to monitor

jobs:
  read_file:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Read content of the text file
      id: readfile
      run: |
        content=$(cat .github/workflows/hello.txt) # Adjust the file path
        echo "file_content=$content" >> $GITHUB_ENV

    - name: Print content to log
      run: |
        echo "Content of the file is:"
        echo "$file_content"  # This will print the content to the workflow log
